### ISSUE TITLE
Obfuscation system may violate MCP EULA.

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#16]
BL's obfuscation system (not OBFUtil, but the BlazeLoader extension of it) may violate MCP's EULA by including MCP obfuscation mappings.  The mappings are not stored in any MCP format, or in the same groupings, but apparently they have a copyright on the mappings themselves(?).  I am not a lawyer, but it someone is who could validate/invalidate this that would be great.  The file in question is https://github.com/BlazeLoader/BlazeLoader/blob/master/res/conf/minecraft_client.obf\

Possible solutions include:
* Create new mappings using Cuchaz's excellent [Enigma](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2162136-enigma-a-tool-for-deobfuscation-of-java-bytecode). 
* Contact MCP for permission to include the mappings, since they are in a non-MCP format
* Include only necessary mappings, since the problem is likely to come from the inclusion of the entire mappings.  Would still be technically violating, however.

**Comment by Sollace** [comment]
I tried to look into this but can't find any copies of their EULA. The only terms available are here: [linky](http://minecraft.gamepedia.com/Programs_and_editors/Mod_Coder_Pack#License_and_terms_of_use)

There's nothing saying we can't use the mappings.

**Comment by Sollace** [comment]
I'm going to close this now. We don't keep a full set of obfuscations anymore, only the items needed for the ONF transformer.
