### ISSUE TITLE
OverrideEventClientHandler has both client and server side code

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#19]
It needs to be split into OverrideEventHandler (with server side) and OverrideEventClientHandler(with client side).  Also splitting up the overrides into separate interfaces would not be a bad idea.

**Comment by Sollace** [comment]
I believe this is no longer an issue. The OverrideEventClientHandler class no longer exists and the current EventHandler classes were all organised correctly last I checked.

>Close?

**Comment by warriordog** [comment]
Yeah this is no longer relevant
