### ISSUE TITLE
ApiWorld is not implemented

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#22]
A long time ago, ApiWorld had a function to add custom world gen.  Unfortunately this was done through the modified mojang classes, so the changes that were made to vanilla are now gone.  The world gen support is still there, however it is not actually attached to the game anymore.  This should be fixed.

**Comment by Sollace** [comment]
ApiWorld has been, if not fully mostly, reimplemented since this was issue made.

>Close?

**Comment by warriordog** [comment]
Closed
