### ISSUE TITLE
Refactor obfuscation system to allow better debug info

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#23]
Currently when an incorrect mapping is input, the only info is a NullPointerException in one of a few places.  The whole system should have null checks added, and IllegalArgumentExceptions thrown with more info.

**Comment by Sollace** [comment]
Did this a long while ago, but never saw the issue.

Attempting to lookup an invalid obfuscation entry will cause a crash with the following message:

    "Unrecognised Obfuscation String: {level}@{name} for TargetType: {type}"
