### ISSUE TITLE
Switch to java 8

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#37]
Since MC now requires java 8, and installs it automatically, there is no reason not to use it.

**Comment by warriordog** [comment]
@Sollace

Would you be ready/able to be ready if I were to go ahead and convert to java 8?  The changes are rather minor, but you will need a JDK 8 available to develop and run.

**Comment by Sollace** [comment]
@warriordog 
Yeah I'm fine with it. Can upgrade sometime after.

**Comment by warriordog** [comment]
@Sollace 

Cool, I will do that once I fix my fork

**Comment by Sollace** [comment]
@warriordog 
I'm all ready to go with java 8. Just so you know.

**Comment by Sollace** [comment]
@SeamusFD 
Seems we can't switch to java 8 quite yet. I've found out MCP can't reobfuscate it's classes so we'll have to wait for them to update first.

Any idea if there is a place to report bugs in MCP?

**Comment by warriordog** [comment]
@Sollace @SeamusFD
#EnigmaMasterRace

**Comment by Sollace** [comment]
@SeamusFD 
Wait how did I?

Sorry Seamus, meant to tag Warriordog there.

@warriordog 
I guess that'll work.Any idea if it's complete (enough)?

**Comment by Sollace** [comment]
I'm going to close this. Blazeloader has been working in java 8 for a while.

Check PR #67 for the MCP fix.
