### ISSUE TITLE
Replacing blocks does not transfer texture

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#48]
When you replace a block with ApiBlock.replacBlock(), the resulting block has the checkerboard "missing texture" texture.

**Comment by warriordog** [comment]
@Sollace

You wrote this part of the code, could you take a look at it?

**Comment by warriordog** [comment]
Actually this is not quite correct, as the default block state will still have a texture.  But the others will be missing.

**Comment by warriordog** [comment]
@Sollace

This is actually quite broken as far as rendering.  When a block is changed like this ALL of it's block states get an odd bug where they will not render until another block in the chunk it updated, as if they are not triggering chunk rebuilds or something.

**Comment by Sollace** [comment]
@warriordog 
Can you show me the code you're using to test it?

I have it working with grass blocks just fine, I'll try it with something that has other states to see how it goes.

**Comment by Sollace** [comment]
@warriordog 
Works fine with dirt but I see I've made some mistakes in replaceBlock. It's not actually doing anything with the original states so I'm going to rewrite it.

**Comment by warriordog** [comment]
@sollace

I did it by swapping stone with a subclass of stone

**Comment by Sollace** [comment]
@warriordog 
Interesting, stone was one of the earlier tests I did and it seemed ok.

Tried it and everything looks fine. Can you confirm it still happens with this code?

    	BlockDeadStone test3 = new BlockDeadStone();
    	test3.setUnlocalizedName("stone");
    	ApiBlock.replaceBlock(Blocks.stone, test3);
    	ApiItem.registerItemBlock(test3, (new ItemMultiTexture(test3, test3, new Function() {
            public String apply(ItemStack stack) {
                return BlockStone.EnumType.byMetadata(stack.getMetadata()).getUnlocalizedName();
            }
            public Object apply(Object stack) {
                return this.apply((ItemStack)stack);
            }
        })).setUnlocalizedName("stone"));

Just change the class of the block on the first line to whatever you have.

**Comment by warriordog** [comment]
I'll try this when we get home

**Comment by warriordog** [comment]
@Sollace 

Using that seems to have fixed it!

**Comment by Sollace** [comment]
@warriordog 
Yup, that looks good. Also if you're calling setUnlocalisedName in the contructor then you won't have to set it anywhere else. 

I've done the rewriting and will do a PR later as soon as I finish one last thing.

**Comment by warriordog** [comment]
Cool, thanks for fixing this!

**Comment by Sollace** [comment]
Of course this one too. (Sorry for spamming)

**Comment by warriordog** [comment]
@Sollace 

I sent you an invite to the BlazeLoader organization, so that you can commit directly to the repo, edit issues, etc.

**Comment by Sollace** [comment]
@warriordog Ok. I will try to find it in my email.
