### ISSUE TITLE
Important events

### ISSUE THREAD

**Issue by warriordog** [BlazeLoader/BlazeLoader#7]
Add some important events:

* Client break/place block
* Server receive break/place block
* (?) Server send break/place block
* Server receive chat
* (?) Server send chat
* Client send chat
* Server mob spawn
* Client switch world
* Client player collide with block
* Server player collide with block

See old issue: https://github.com/warriordog/BlazeLoader/issues/8

**Comment by Sollace** [comment]
Finally got around to looking at these.

Here's what I've found:
Events matched to an existing or new one that can be used to do the same thing.

Client/Server player collide with block -> PlayerListener.onPlayerCollideWithBlock (wip)
Client switch world -> ClientWorldListener.onWorldChanged
Server mob spawn -> WorldListener.onEntitySpawned (wip) (called when an entity is added to the world)
Client send chat -> OutboundChatListener.onSendChatMessage (liteloader)
Server send chat -> OutboundChatListener.onSendChatMessage (liteloader) (presumed)
Server recieve chat -> ServerChatFilter.onChat (liteloader)
Server send break/place block -> x (not needed see below)
Server recieve break/place block -> x (not needed see below)
Client (or server) break/place block -> BlockChangedListener.onPlace/BreakBlock (added) (called when a player places/breaks a block)

**Comment by Sollace** [comment]
Ok, most of these events are now in place. See #73 for the changes.

I'm going to close this now, and anyone can make a new one for any events I might have missed.
